Repository aai-institute/nnbench, pull requests merged in 2024-02, with the labels that each got.

#39 Add benchmark organization guide
  docs/guides/organization.md
  mkdocs.yml
Labels: documentation

#57 Add customization user guide
  docs/guides/benchmarks.md
  docs/guides/customization.md
  docs/guides/organization.md
  docs/quickstart.md
  examples/mnist/mnist.py
  mkdocs.yml
  src/nnbench/__init__.py
  src/nnbench/runner.py
  tests/test_argcheck.py
  tests/test_runner.py
Labels: documentation

#59 Add more default information to benchmark JSON result
  src/nnbench/core.py
  src/nnbench/runner.py
Labels: enhancement

#55 Add benchmark runners user guide
  docs/guides/runners.md
  mkdocs.yml
Labels: documentation

#54 Add test coverage
  tests/conftest.py
  tests/test_benchmarks_multidir_collection/benchmark_in_another_dir.py
  tests/test_decorators.py
  tests/test_runner.py
  tests/test_utils.py
Labels: tests

#60 Final docs changes in preparation for v0.1.0
  README.md
  pyproject.toml
Labels: documentation

#64 Add git info and Python package info providers
  pyproject.toml
  requirements-dev.txt
  requirements-docs.txt
  src/nnbench/context.py
  tests/test_context.py
Labels: enhancement

#83 Unify batching in file drivers, remove read/write stubs on base reporter
  examples/mnist/mnist.py
  src/nnbench/reporter/__init__.py
  src/nnbench/reporter/base.py
  src/nnbench/reporter/duckdb_sql.py
  src/nnbench/reporter/file.py
Labels: refactor

#84 Add compression algorithms facility to file IO
  src/nnbench/reporter/file.py
Labels: enhancement

#85 Add BQ example to showcase cloud streaming of benchmark records
  .pre-commit-config.yaml
  docs/tutorials/bq.md
  examples/bq/benchmarks.py
  examples/bq/bq.py
  mkdocs.yml
  src/nnbench/types.py
Labels: documentation

#90 Restructure test suite and add file IO roundtrip tests
  pyproject.toml
  requirements-dev.txt
  requirements-docs.txt
  src/nnbench/context.py
  src/nnbench/reporter/file.py
  src/nnbench/types.py
  tests/benchmarks/argchecks.py
  tests/benchmarks/standard.py
  tests/benchmarks/tags.py
  tests/conftest.py
  tests/test_argcheck.py
  tests/test_benchmarks_multidir_collection/benchmark_in_another_dir.py
  tests/test_context.py
  tests/test_fileio.py
  tests/test_runner.py
  tests/test_types.py
Labels: tests
